
version: 0.0
os: linux
files:
  - source: /
    destination: /home/pi/brain/
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: /shells/after_install.sh
      timeout: 300
      runas: root