from pathlib import Path

from setuptools import setup, find_namespace_packages

source_root = Path(".")
with (source_root / "README.md").open(encoding="utf-8") as f:
    long_description = f.read()

with (source_root / "requirements.txt").open(encoding="utf8") as f:
    requirements = list(filter(lambda dep: dep != '-e .', f.read().strip().split('\n')))

version = '0.0.2'

with (source_root / "src" / "command" / "version.py").open(
        "w", encoding="utf-8"
) as f:
    f.writelines(
        [
            '"""This file is auto-generated by setup.py, please do not alter."""\n',
            f'__version__ = "{version}"\n',
            "",
        ]
    )

setup(
    name='growx-robot-layer-software',
    package_dir={'': 'src'},
    packages=find_namespace_packages(where='src'),
    include_package_data=True,
    version=version,
    description='The GROWx Horizontal Robot',
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    author='GROWx',
    url='https://github.com/newcraftgroup/nci-dsm-tabs',
    python_requires='>=3.9',
    install_requires=requirements,
    license='Copyright (C) GROWx/Growy - All Rights Reserved',
    entry_points={
        'console_scripts': [
            "start-robot=command.bot:main"
        ]
    }
)
